import java.sql.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {


    public static void main(String[] args) throws SQLException {
        Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/devdb"
                , "dev", "star");
        String query = "select * from courses";
        PreparedStatement st = conn.prepareStatement(query);
        //ResultSet rs = st.executeQuery("select * from courses");
        ResultSet rs = st.executeQuery();
        while (rs.next()){
            System.out.println(rs.getString(1)+" title: "+rs.getString(2));
        }
        rs.close();
        st.close();
        conn.close();
    }
}
